export const FETCH_PACIENTES_START = 'FETCH_PACIENTES';
export const FETCH_PACIENTES_SUCCESS = 'FETCH_PACIENTES_SUCCESS';
export const FETCH_PACIENTES_FAILURE = 'FETCH_PACIENTES_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const LOGOUT = 'LOGOUT';

