# Generated by Django 3.1 on 2020-09-29 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilterapeuta',
            old_name='UserAccount',
            new_name='userAccount',
        ),
    ]
