# Generated by Django 3.1 on 2020-09-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terapia',
            old_name='UserAccount',
            new_name='userAccount',
        ),
    ]
