# Generated by Django 3.1 on 2020-10-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20200929_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapia',
            name='captacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terapia',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='terapia',
            name='motivoConsulta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terapia',
            name='tipoTerapia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
