# Generated by Django 3.1 on 2020-09-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_terapeuta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='terapeuta',
            new_name='userAccount',
        ),
    ]
