# Generated by Django 3.1 on 2020-10-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20201002_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTerapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTerapia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=False)),
                ('fechaSesion', models.DateField()),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.terapia')),
            ],
        ),
    ]
