# Generated by Django 3.1 on 2020-10-03 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20201002_2238'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terapia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='userAccount',
            field=models.ManyToManyField(through='terapia.Terapia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Sesion',
        ),
        migrations.DeleteModel(
            name='Terapia',
        ),
    ]
