# Generated by Django 3.1 on 2020-08-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('ApellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('comunaDeResidencia', models.CharField(max_length=100)),
                ('orientacionSexual', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('ocupacionProfecion', models.CharField(max_length=100)),
                ('nombreContactoEmergencia', models.CharField(max_length=100)),
                ('telefonoContactoEmergencia', models.CharField(max_length=100)),
                ('emailContactoEmergencia', models.CharField(max_length=100)),
                ('nombrePsiquiatra', models.CharField(max_length=100)),
                ('emailPsiquiatra', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('ApellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('comunaDeResidencia', models.CharField(max_length=100)),
                ('orientacionSexual', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('director', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
